version: '3.2'

services:
  mysql:
    image: mysql
    restart: always
    environment: 
      MYSQL_USER: impact
      MYSQL_PASSWORD: impact
      MYSQL_DATABASE: impact
      MYSQL_ROOT_PASSWORD: root
      DATABASE_PORT: 3306
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  web:
    image: nginx
    volumes:
      - /vagrant/services/nginx:/etc/nginx/conf.d/mysite.template
      - /vagrant/services/nginx/site/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - backend
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80

  api:
    image: hellojava
    volumes:
      - /tmp
    ports:
      - "7777:8080"
    networks:
      - backend
    depends_on:
      - mysql  

  jenkins:
    image: jenkins:2.60.3
    restart: unless-stopped
    ports:
      - target: 8080
        published: 9090
        protocol: tcp
        mode: host
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock    

networks:
  backend:

volumes:
  mysql-data:
  jenkins-home: