version: '3.1'

services:
    mysql:
        image: mysql
        environment: 
            MYSQL_USER: impact
            MYSQL_DATABASE: impact
            MYSQL_ROOT_PASSWORD: root
        deploy:
            placement:
                constraints:
                    - node.role==manager
        ports:
            - "3306:3306"                    
        network:
            - backend

            
