version: '3.1'

services:
   mysql:
     image: mysql
     environment: 
       MYSQL_USER: impact
       MYSQL_DATABASE: impact
       MYSQL_ROOT_PASSWORD: root
     deploy:
       placement:
         constraints:
           - node.role==manager
     ports:
       - "3306:3306"
    # network:
    #   - backend
  web:
    image: nginx
    volumes:
      - /vagrant/services/nginx:/etc/nginx/conf.d/mysite.template
    ports:
      - "8080:80"
    # networks:
    #   - backend
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

#networks:
#  - backend
#volumes:
#  - backend-data
#  - frontend-data
