---
# tasks file for ACS
- name: Start Docker Swarm
  shell: docker swarm init --advertise-addr 192.168.99.201

- name: Build Docker Container for Java Hello World
  shell: docker build /vagrant/services/springboot/complete/. --tag hellojava:1.0 hellojava

#- name: Copy VueJS Files to target directory
#  shell: docker build /vagrant/services/springboot/complete/. --tag hellojava:1.0 hellojava  

# - name: Copiar o arquivo modoDesenvTrue.sql
#   template:
#     src: modoDesenvFalse.sql.j2
#     dest: "/public/modoDesenvTrue.sql"
#     owner: oracle
#     group: oracle
#     mode: 0777  

- name: Deploy Docker Swarm
  shell: docker stack deploy --compose-file /vagrant/docker-compose.yml impact