---
- hosts: manager
  connection: local
  name: manager servers
  become: yes

#  vars_files:
#    - vars/main.yml

  pre_tasks:
    - name: Install python-pip
      apt: name={{item}} state=present
      with_items:
        - python-pip

    - name: Install docker-py
      shell: pip install docker-py

#  roles:
#    - roles/bonis.debug

  tasks:
    - import_tasks: tasks/main.yml

#  pos_tasks:
#    - name: Remove the Apache test page.
#      file:
#        path: /var/www/html/index.html
#        state: absent