---
- hosts: manager
  connection: local
  name: manager servers
  become: yes

#  vars_files:
#    - vars/main.yml

#  pre_tasks:
#    - name: installing repo for Python in Ubuntu
#      apt_repository: repo='ppa:fkrull/deadsnakes' state=present

#  roles:
#    - roles/bonis.debug

  tasks:
    - import_tasks: tasks/main.yml

#  pos_tasks:
#    - name: Remove the Apache test page.
#      file:
#        path: /var/www/html/index.html
#        state: absent