---
#install java

#- name: Download Maven
#  shell: sudo wget http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz

#- name: Install Maven
#  shell: sudo tar -xvzf apache-maven-3.3.9-bin.tar.gz

#- name: Rename Maven
#  shell: sudo mv apache-maven-3.3.9 /opt/maven

#- name: Configure Profile
#  shell: sudo touch /etc/profile.d/mavenenv.sh
#  shell: echo "export M2_HOME=/opt/maven" >> /etc/profile.d/mavenenv.sh
#  shell: echo "export PATH=${M2_HOME}/bin:${PATH}" >> /etc/profile.d/mavenenv.sh

#- name: Source Maven Profile
#  shell: source /etc/profile.d/mavenenv.sh

#- name: Leaving Docker Swarm
#  shell: docker swarm leave --force

#- name: Compile 
#  shell: "cd /vagrant/services/spring/ && mvn clean install package"

- name: Start Docker Swarm
  shell: docker swarm init --advertise-addr 192.168.99.201

- name: Pull Nginx Image
  docker_image:
    name: nginx
    state: present
    tag: latest  

- name: Pull MySQL Image
  docker_image:
    name: mysql
    state: present
    tag: latest  

- name: Pull Java 8 Image
  docker_image:
    name: java:8
    state: present
    tag: latest     

- name: Build Docker Container for Java Hello World
  shell: "cd /vagrant/services/spring/ && docker build . --tag hellojava:1.0 --tag hellojava"

# - name: Copy VueJS Files to target directory
#   command: cp -r /vagrant/services/nginx/site/dist/{{ item }} /usr/share/nginx/html
#   with_items:
#    - "index.html"
#    - "static/"

- name: Deploy Docker Swarm
  shell: docker stack deploy --compose-file /vagrant/docker-compose.yml impact
