---
- name: Leaving Docker Swarm
  shell: docker swarm leave --force
  ignore_errors: yes

- name: Start Docker Swarm
  shell: docker swarm init --advertise-addr 192.168.99.201
  ignore_errors: yes

- name: Pull Nginx Image
  docker_image:
    name: nginx
    state: present
    tag: latest  

- name: Pull MySQL Image
  docker_image:
    name: mysql
    state: present
    tag: latest  

- name: Pull Java 8 Image
  docker_image:
    #name: java:8
    name: openjdk:8-jdk
    state: present
    tag: latest

- name: Pull Jenkins Image
  docker_image:
    name: jenkins
    state: present
    tag: 2.60.3  

- name: Build Docker Container for Java Hello World
  shell: "cd /vagrant/services/spring/ && docker build . --tag hellojava:1.0 --tag hellojava"

# - name: Copy VueJS Files to target directory
#   command: cp -r /vagrant/services/nginx/site/dist/{{ item }} /usr/share/nginx/html
#   with_items:
#    - "index.html"
#    - "static/"

- name: Deploy Docker Swarm
  shell: docker stack deploy --compose-file /vagrant/docker-compose.yml impact

- name: Set Jenkins Password
  shell: ID=$(docker container ls -q -f "label=com.docker.swarm.service.name=jenkins") && docker container exec -it $ID cat /var/jenkins_home/secrets/initialAdminPassword

